// Find the sum of all numbers in an N×N grid generated by loops.

package Session08;

import java.util.Scanner;

public class SumOfNbyNGrid {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        System.out.println("Enter row n number : ");
        int rowN = sc.nextInt();
        System.out.println("Enter the column n number: ");
        int colN = sc.nextInt();
        int sum = 0;
        for(int i = 1; i <= rowN; i++){
            for(int j = 1; j<=colN; j++){
                System.out.print(i+" ");
                sum += i;
            }
            System.out.println();
        }
        System.out.println("The total sum of N x N Grid is : "+sum);
        sc.close();
    }
}
